# Automatically generated by configure - do not modify
SRC_PATH=/home/nathan/qemu-0.15.1/roms/seabios
CC=arm-linux-androideabi-gcc
BCC=bcc
CPP=arm-linux-androideabi-cpp
OBJCOPY=objcopy
IASL=iasl
LD=arm-linux-androideabi-ld
