/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libSDL_jni_libSDLproxy */

#ifndef _Included_libSDL_jni_libSDLproxy
#define _Included_libSDL_jni_libSDLproxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLmain
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_libSDL_jni_libSDLproxy_libSDLmain
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLcheckloaded
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_libSDL_jni_libSDLproxy_libSDLcheckloaded
  (JNIEnv *, jclass);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLcleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_libSDL_jni_libSDLproxy_libSDLcleanup
  (JNIEnv *, jclass);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLpause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_libSDL_jni_libSDLproxy_libSDLpause
  (JNIEnv *, jclass);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLresume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_libSDL_jni_libSDLproxy_libSDLresume
  (JNIEnv *, jclass);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLisportrait
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_libSDL_jni_libSDLproxy_libSDLisportrait
  (JNIEnv *, jclass);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLnotifytouch
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_libSDL_jni_libSDLproxy_libSDLnotifytouch
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLnotifyjoystick
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_libSDL_jni_libSDLproxy_libSDLnotifyjoystick
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLnotifytrackpad
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_libSDL_jni_libSDLproxy_libSDLnotifytrackpad
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLnotifykey
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_libSDL_jni_libSDLproxy_libSDLnotifykey
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     libSDL_jni_libSDLproxy
 * Method:    libSDLupdatebuffer
 * Signature: (Ljava/nio/Buffer;II)I
 */
JNIEXPORT jint JNICALL Java_libSDL_jni_libSDLproxy_libSDLupdatebuffer
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
